/*
 * This file is generated by jOOQ.
 */
package com.worldofcasus.professions.database.jooq.casus.tables.records;


import com.worldofcasus.professions.database.jooq.casus.tables.CharacterProfession;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterProfessionRecord extends TableRecordImpl<CharacterProfessionRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>casus.character_profession.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>casus.character_profession.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>casus.character_profession.profession_id</code>.
     */
    public void setProfessionId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>casus.character_profession.profession_id</code>.
     */
    public Integer getProfessionId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CharacterProfession.CHARACTER_PROFESSION.CHARACTER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CharacterProfession.CHARACTER_PROFESSION.PROFESSION_ID;
    }

    @Override
    public Integer component1() {
        return getCharacterId();
    }

    @Override
    public Integer component2() {
        return getProfessionId();
    }

    @Override
    public Integer value1() {
        return getCharacterId();
    }

    @Override
    public Integer value2() {
        return getProfessionId();
    }

    @Override
    public CharacterProfessionRecord value1(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public CharacterProfessionRecord value2(Integer value) {
        setProfessionId(value);
        return this;
    }

    @Override
    public CharacterProfessionRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterProfessionRecord
     */
    public CharacterProfessionRecord() {
        super(CharacterProfession.CHARACTER_PROFESSION);
    }

    /**
     * Create a detached, initialised CharacterProfessionRecord
     */
    public CharacterProfessionRecord(Integer characterId, Integer professionId) {
        super(CharacterProfession.CHARACTER_PROFESSION);

        setCharacterId(characterId);
        setProfessionId(professionId);
    }
}
