/*
 * This file is generated by jOOQ.
 */
package com.worldofcasus.professions.database.jooq.casus.tables.records;


import com.worldofcasus.professions.database.jooq.casus.tables.CharacterStamina;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterStaminaRecord extends UpdatableRecordImpl<CharacterStaminaRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>casus.character_stamina.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>casus.character_stamina.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>casus.character_stamina.stamina</code>.
     */
    public void setStamina(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>casus.character_stamina.stamina</code>.
     */
    public Integer getStamina() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CharacterStamina.CHARACTER_STAMINA.CHARACTER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CharacterStamina.CHARACTER_STAMINA.STAMINA;
    }

    @Override
    public Integer component1() {
        return getCharacterId();
    }

    @Override
    public Integer component2() {
        return getStamina();
    }

    @Override
    public Integer value1() {
        return getCharacterId();
    }

    @Override
    public Integer value2() {
        return getStamina();
    }

    @Override
    public CharacterStaminaRecord value1(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public CharacterStaminaRecord value2(Integer value) {
        setStamina(value);
        return this;
    }

    @Override
    public CharacterStaminaRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterStaminaRecord
     */
    public CharacterStaminaRecord() {
        super(CharacterStamina.CHARACTER_STAMINA);
    }

    /**
     * Create a detached, initialised CharacterStaminaRecord
     */
    public CharacterStaminaRecord(Integer characterId, Integer stamina) {
        super(CharacterStamina.CHARACTER_STAMINA);

        setCharacterId(characterId);
        setStamina(stamina);
    }
}
