/*
 * This file is generated by jOOQ.
 */
package com.worldofcasus.professions.database.jooq.casus.tables;


import com.worldofcasus.professions.database.jooq.casus.Casus;
import com.worldofcasus.professions.database.jooq.casus.Keys;
import com.worldofcasus.professions.database.jooq.casus.tables.records.NodeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Node extends TableImpl<NodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>casus.node</code>
     */
    public static final Node NODE = new Node();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NodeRecord> getRecordType() {
        return NodeRecord.class;
    }

    /**
     * The column <code>casus.node.id</code>.
     */
    public final TableField<NodeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>casus.node.name</code>.
     */
    public final TableField<NodeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>casus.node.world</code>.
     */
    public final TableField<NodeRecord, String> WORLD = createField(DSL.name("world"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>casus.node.min_x</code>.
     */
    public final TableField<NodeRecord, Integer> MIN_X = createField(DSL.name("min_x"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>casus.node.min_y</code>.
     */
    public final TableField<NodeRecord, Integer> MIN_Y = createField(DSL.name("min_y"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>casus.node.min_z</code>.
     */
    public final TableField<NodeRecord, Integer> MIN_Z = createField(DSL.name("min_z"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>casus.node.max_x</code>.
     */
    public final TableField<NodeRecord, Integer> MAX_X = createField(DSL.name("max_x"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>casus.node.max_y</code>.
     */
    public final TableField<NodeRecord, Integer> MAX_Y = createField(DSL.name("max_y"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>casus.node.max_z</code>.
     */
    public final TableField<NodeRecord, Integer> MAX_Z = createField(DSL.name("max_z"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>casus.node.required_profession_id</code>.
     */
    public final TableField<NodeRecord, Integer> REQUIRED_PROFESSION_ID = createField(DSL.name("required_profession_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Node(Name alias, Table<NodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Node(Name alias, Table<NodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>casus.node</code> table reference
     */
    public Node(String alias) {
        this(DSL.name(alias), NODE);
    }

    /**
     * Create an aliased <code>casus.node</code> table reference
     */
    public Node(Name alias) {
        this(alias, NODE);
    }

    /**
     * Create a <code>casus.node</code> table reference
     */
    public Node() {
        this(DSL.name("node"), null);
    }

    public <O extends Record> Node(Table<O> child, ForeignKey<O, NodeRecord> key) {
        super(child, key, NODE);
    }

    @Override
    public Schema getSchema() {
        return Casus.CASUS;
    }

    @Override
    public Identity<NodeRecord, Integer> getIdentity() {
        return (Identity<NodeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NodeRecord> getPrimaryKey() {
        return Keys.KEY_NODE_PRIMARY;
    }

    @Override
    public List<UniqueKey<NodeRecord>> getKeys() {
        return Arrays.<UniqueKey<NodeRecord>>asList(Keys.KEY_NODE_PRIMARY, Keys.KEY_NODE_NODE_NAME_UINDEX);
    }

    @Override
    public List<ForeignKey<NodeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<NodeRecord, ?>>asList(Keys.NODE_PROFESSION_ID_FK);
    }

    public Profession profession() {
        return new Profession(this, Keys.NODE_PROFESSION_ID_FK);
    }

    @Override
    public Node as(String alias) {
        return new Node(DSL.name(alias), this);
    }

    @Override
    public Node as(Name alias) {
        return new Node(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Node rename(String name) {
        return new Node(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Node rename(Name name) {
        return new Node(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
