/*
 * This file is generated by jOOQ.
 */
package com.worldofcasus.professions.database.jooq.casus.tables;


import com.worldofcasus.professions.database.jooq.casus.Casus;
import com.worldofcasus.professions.database.jooq.casus.Keys;
import com.worldofcasus.professions.database.jooq.casus.tables.records.ProfessionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profession extends TableImpl<ProfessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>casus.profession</code>
     */
    public static final Profession PROFESSION = new Profession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessionRecord> getRecordType() {
        return ProfessionRecord.class;
    }

    /**
     * The column <code>casus.profession.id</code>.
     */
    public final TableField<ProfessionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>casus.profession.name</code>.
     */
    public final TableField<ProfessionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    private Profession(Name alias, Table<ProfessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Profession(Name alias, Table<ProfessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>casus.profession</code> table reference
     */
    public Profession(String alias) {
        this(DSL.name(alias), PROFESSION);
    }

    /**
     * Create an aliased <code>casus.profession</code> table reference
     */
    public Profession(Name alias) {
        this(alias, PROFESSION);
    }

    /**
     * Create a <code>casus.profession</code> table reference
     */
    public Profession() {
        this(DSL.name("profession"), null);
    }

    public <O extends Record> Profession(Table<O> child, ForeignKey<O, ProfessionRecord> key) {
        super(child, key, PROFESSION);
    }

    @Override
    public Schema getSchema() {
        return Casus.CASUS;
    }

    @Override
    public Identity<ProfessionRecord, Integer> getIdentity() {
        return (Identity<ProfessionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProfessionRecord> getPrimaryKey() {
        return Keys.KEY_PROFESSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProfessionRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfessionRecord>>asList(Keys.KEY_PROFESSION_PRIMARY, Keys.KEY_PROFESSION_UK_PROFESSION_NAME);
    }

    @Override
    public Profession as(String alias) {
        return new Profession(DSL.name(alias), this);
    }

    @Override
    public Profession as(Name alias) {
        return new Profession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Profession rename(String name) {
        return new Profession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profession rename(Name name) {
        return new Profession(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
