/*
 * This file is generated by jOOQ.
 */
package com.worldofcasus.professions.database.jooq.casus;


import com.worldofcasus.professions.database.jooq.casus.tables.CharacterProfession;
import com.worldofcasus.professions.database.jooq.casus.tables.CharacterStamina;
import com.worldofcasus.professions.database.jooq.casus.tables.Node;
import com.worldofcasus.professions.database.jooq.casus.tables.NodeItem;
import com.worldofcasus.professions.database.jooq.casus.tables.Profession;


/**
 * Convenience access to all tables in casus.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>casus.character_profession</code>.
     */
    public static final CharacterProfession CHARACTER_PROFESSION = CharacterProfession.CHARACTER_PROFESSION;

    /**
     * The table <code>casus.character_stamina</code>.
     */
    public static final CharacterStamina CHARACTER_STAMINA = CharacterStamina.CHARACTER_STAMINA;

    /**
     * The table <code>casus.node</code>.
     */
    public static final Node NODE = Node.NODE;

    /**
     * The table <code>casus.node_item</code>.
     */
    public static final NodeItem NODE_ITEM = NodeItem.NODE_ITEM;

    /**
     * The table <code>casus.profession</code>.
     */
    public static final Profession PROFESSION = Profession.PROFESSION;
}
